config/routes.rb
Ordersheet::Application.routes.draw do
  get "top/index"
  resources :order_dates

  resources :unit_masters

  resources :position_masters

  resources :payment_site_masters

  resources :order_arrival_dates

  resources :order_break_times

  resources :order_charge_people

  resources :order_infos

  resources :business_masters

  resources :project_masters

  resources :company_masters

  resources :employee_masters

  root to: 'top#index'

end

app/models/business_master.rb
class BusinessMaster < ActiveRecord::Base
  has_many :order_info, foreign_key: :business_id
end

app/controllers/business_masters_controller.rb
class BusinessMastersController < ApplicationController
  before_action :set_business_master, only: [:show, :edit, :update, :destroy]

  # GET /business_masters
  # GET /business_masters.json
  def index
    @business_masters = BusinessMaster.all
  end

  # GET /business_masters/1
  # GET /business_masters/1.json
  def show
  end

  # GET /business_masters/new
  def new
    @business_master = BusinessMaster.new
  end

  # GET /business_masters/1/edit
  def edit
  end

  # POST /business_masters
  # POST /business_masters.json
  def create
    @business_master = BusinessMaster.new(business_master_params)

    respond_to do |format|
      if @business_master.save
        format.html { redirect_to @business_master, notice: 'Business master was successfully created.' }
        format.json { render 'show', status: :created, location: @business_master }
      else
        format.html { render 'new' }
        format.json { render json: @business_master.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /business_masters/1
  # PATCH/PUT /business_masters/1.json
  def update
    respond_to do |format|
      if @business_master.update(business_master_params)
        format.html { redirect_to @business_master, notice: 'Business master was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render 'edit' }
        format.json { render json: @business_master.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /business_masters/1
  # DELETE /business_masters/1.json
  def destroy
    @business_master.destroy
    respond_to do |format|
      format.html { redirect_to business_masters_url }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_business_master
      @business_master = BusinessMaster.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def business_master_params
      params.require(:business_master).permit(:business_name)
    end
end

app/views/business_masters/_form.html.erb
<%= form_for(business_master) do |f| %>
  <% if business_master.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(business_master.errors.count, "error") %> prohibited this business_master from being saved:</h2>

      <ul>
      <% business_master.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label "業務名" %><br />
    <%= f.text_field :business_name %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/business_masters/edit.html.erb
<%= render '/layouts/header' %>
<h2>業務マスタ更新</h2>

<%= render 'form', business_master: @business_master %>

<%= link_to '照会', @business_master %> |
<%= link_to '戻る', business_masters_path %>

app/views/business_masters/index.html.erb
<%= render '/layouts/header' %>
<h2>業務マスタ一覧</h2>
<%= link_to '新規登録', new_business_master_path %>
<br ><table id="default">
  <thead>
    <tr>
      <th>業務ID</th>
      <th>業務名</th>
      <th colspan=3></th>
    </tr>
  </thead>

  <tbody>
    <% @business_masters.each do |business_master| %>
    <tr>
      <td><%= business_master.id %></td>
      <td><%= business_master.business_name %></td>
      <td><%= link_to '照会', business_master %></td>
      <td><%= link_to '更新', edit_business_master_path(business_master) %></td>
      <td><%= link_to '削除', business_master, method: :delete, data: { confirm: '削除してよろしいですか?' } %></td>
    </tr>
    <% end %>
  </tbody>
</table>

<br />

app/views/business_masters/new.html.erb
<%= render '/layouts/header' %>
<h2>業務マスタ　新規登録</h2>

# 子供のパーツではインスタンス変数を使わないようにしたほうが再利用しやすくなる
# そのため、@business_masterをbusiness_masterとして渡している
<%= render 'form', business_master: @business_master %>

app/views/business_masters/show.html.erb
<%= render '/layouts/header' %>
<h2>業務マスタ　照会</h2>
<p>
  <strong>業務名</strong>
  <%= @business_master.business_name %>
</p>
<%= link_to '更新', edit_business_master_path(@business_master) %> |
<%= link_to '戻る', business_masters_path %>