config/routes.rb
Ordersheet::Application.routes.draw do
  get "top/index"
  resources :order_dates

  resources :unit_masters

  resources :position_masters

  resources :payment_site_masters

  resources :order_arrival_dates

  resources :order_break_times

  resources :order_charge_people

  resources :order_infos

  resources :business_masters

  resources :project_masters

  resources :company_masters

  resources :employee_masters

  root to: 'top#index'

end

app/models/order_break_time.rb
class OrderBreakTime < ActiveRecord::Base
  belongs_to :order_info
end

app/controllers/order_break_times_controller.rb
class OrderBreakTimesController < ApplicationController
  before_action :set_order_break_time, only: [:show, :edit, :update, :destroy]

  # GET /order_break_times
  # GET /order_break_times.json
  def index
    @order_break_times = OrderBreakTime.all
  end

  # GET /order_break_times/1
  # GET /order_break_times/1.json
  def show
  end

  # GET /order_break_times/new
  def new
    @order_break_time = OrderBreakTime.new
  end

  # GET /order_break_times/1/edit
  def edit
  end

  # POST /order_break_times
  # POST /order_break_times.json
  def create
    @order_break_time = OrderBreakTime.new(order_break_time_params)

    respond_to do |format|
      if @order_break_time.save
        format.html { redirect_to @order_break_time, notice: 'Order break time was successfully created.' }
        format.json { render 'show', status: :created, location: @order_break_time }
      else
        format.html { render 'new' }
        format.json { render json: @order_break_time.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /order_break_times/1
  # PATCH/PUT /order_break_times/1.json
  def update
    respond_to do |format|
      if @order_break_time.update(order_break_time_params)
        format.html { redirect_to @order_break_time, notice: 'Order break time was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render 'edit' }
        format.json { render json: @order_break_time.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /order_break_times/1
  # DELETE /order_break_times/1.json
  def destroy
    @order_break_time.destroy
    respond_to do |format|
      format.html { redirect_to order_break_times_url }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_order_break_time
      @order_break_time = OrderBreakTime.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def order_break_time_params
      params.require(:order_break_time).permit(:order_id, :break_start_time, :break_end_time)
    end
end

app/views/order_break_times/_form.html.erb
<%= form_for(order_break_time) do |f| %>
  <% if order_break_time.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(order_break_time.errors.count, "error") %> prohibited this order_break_time from being saved:</h2>

      <ul>
      <% order_break_time.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :order_id %><br />
    <%= f.number_field :order_id %>
  </div>
  <div class="field">
    <%= f.label :break_start_time %><br />
    <%= f.time_select :break_start_time %>
  </div>
  <div class="field">
    <%= f.label :break_end_time %><br />
    <%= f.time_select :break_end_time %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/order_break_times/edit.html.erb
<h1>Editing order_break_time</h1>

<%= render 'form', order_break_time: @order_break_time %>

<%= link_to 'Show', @order_break_time %> |
<%= link_to 'Back', order_break_times_path %>

app/views/order_break_times/index.html.erb
<h1>Listing order_break_times</h1>

<table>
  <thead>
    <tr>
      <th>Order</th>
      <th>Break start time</th>
      <th>Break end time</th>
      <th></th>
      <th></th>
      <th></th>
    </tr>
  </thead>

  <tbody>
    <% @order_break_times.each do |order_break_time| %>
    <tr>
      <td><%= order_break_time.order_id %></td>
      <td><%= order_break_time.break_start_time %></td>
      <td><%= order_break_time.break_end_time %></td>
      <td><%= link_to 'Show', order_break_time %></td>
      <td><%= link_to 'Edit', edit_order_break_time_path(order_break_time) %></td>
      <td><%= link_to 'Destroy', order_break_time, method: :delete, data: { confirm: 'Are you sure?' } %></td>
    </tr>
    <% end %>
  </tbody>
</table>

<br />

<%= link_to 'New Order break time', new_order_break_time_path %>

app/views/order_break_times/new.html.erb
<h1>New order_break_time</h1>

<%= render 'form', order_break_time: @order_break_time %>

<%= link_to 'Back', order_break_times_path %>

app/views/order_break_times/show.html.erb
<p>
  <strong>Order:</strong>
  <%= @order_break_time.order_id %>
</p>

<p>
  <strong>Break start time:</strong>
  <%= @order_break_time.break_start_time %>
</p>

<p>
  <strong>Break end time:</strong>
  <%= @order_break_time.break_end_time %>
</p>


<%= link_to 'Edit', edit_order_break_time_path(@order_break_time) %> |
<%= link_to 'Back', order_break_times_path %>