config/routes.rb
Ordersheet::Application.routes.draw do
  get "top/index"
  resources :order_dates

  resources :unit_masters

  resources :position_masters

  resources :payment_site_masters

  resources :order_arrival_dates

  resources :order_break_times

  resources :order_charge_people

  resources :order_infos

  resources :business_masters

  resources :project_masters

  resources :company_masters

  resources :employee_masters

  root to: 'top#index'

end

app/models/employee_master.rb
class EmployeeMaster < ActiveRecord::Base
   validates_presence_of :employee_cd, :employee_name, :employee_name_kana, :position_id, :unit_id,
       :message => 'が入力されていません。'
  belongs_to :position_master, foreign_key: :position_id
  belongs_to :unit_master, foreign_key: :unit_id
end

app/controllers/employee_masters_controller.rb
class EmployeeMastersController < ApplicationController
  before_action :set_employee_master, only: [:show, :edit, :update, :destroy]

  # GET /employee_masters
  # GET /employee_masters.json
  def index
    @employee_masters = EmployeeMaster.all
    byebug
    @employee_masters
  end

  # GET /employee_masters/1
  # GET /employee_masters/1.json
  def show
  end

  # GET /employee_masters/new
  def new
    @employee_master = EmployeeMaster.new
    set_masters;
  end

  # GET /employee_masters/1/edit
  def edit
    set_masters;
  end

  # POST /employee_masters
  # POST /employee_masters.json
  def create
    @employee_master = EmployeeMaster.new(employee_master_params)

    respond_to do |format|
      if @employee_master.save
        format.html { redirect_to @employee_master, notice: '社員情報が作成されました' }
        format.json { render action: 'show', status: :created, location: @employee_master }
      else
        set_masters;
        format.html { render 'new' }
        format.json { render json: @employee_master.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /employee_masters/1
  # PATCH/PUT /employee_masters/1.json
  def update
    respond_to do |format|
      if @employee_master.update(employee_master_params)
        format.html { redirect_to @employee_master, notice: '社員情報が更新されました' }
        format.json { head :no_content }
      else
        format.html { render 'edit' }
        format.json { render json: @employee_master.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /employee_masters/1
  # DELETE /employee_masters/1.json
  def destroy
    @employee_master.destroy
    respond_to do |format|
      format.html { redirect_to employee_masters_url }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_employee_master
      @employee_master = EmployeeMaster.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def employee_master_params
      params.require(:employee_master).permit(:employee_cd, :employee_name, :employee_name_kana, :position_id, :unit_id, :email_address1, :emai_address2, :postal_cd, :address1, :address2, :tel_no, :fax_no, :mobile_tel_no1, :mobile_tel_no2, :emergency_tel_no, :birth_date, :station, :birth_place, :education_level, :other)
    end
    def set_masters
        @position_masters = PositionMaster.all
        @unit_masters = UnitMaster.all
    end
end

app/views/employee_masters/_form.html.erb
<%= form_for(employee_master) do |f| %>
  <% if employee_master.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(employee_master.errors.count, "error") %> prohibited this employee_master from being saved:</h2>

      <ul>
      <% employee_master.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>,
  <% end %>

  <div class="field">
    <%= f.label "社員番号" %><br />
    <%= f.text_field :employee_cd %>
  </div>
  <div class="field">
    <%= f.label "氏名（かな）" %><br />
    <%= f.text_field :employee_name %>
  </div>
  <div class="field">
    <%= f.label "氏名（かな）" %><br />
    <%= f.text_field :employee_name_kana %>
  </div>
  <div class="field">
    <%= f.label "職制" %><br />
    <%= f.select :position_id, position_masters.all.map{|position| [position.position_name, position.id]}, :include_blank => true %>
  </div>
  <div class="field">
    <%= f.label "部署名" %><br />
    <%= f.select :unit_id, unit_masters.all.map{|unit| [unit.unit_name, unit.id]}, :include_blank => true %>
  </div>
  <div class="field">
    <%= f.label "eメールアドレス1" %><br />
    <%= f.text_field :email_address1 %>
  </div>
  <div class="field">
    <%= f.label "eメールアドレス2" %><br />
    <%= f.text_field :emai_address2 %>
  </div>
  <div class="field">
    <%= f.label "郵便番号" %><br />
    <%= f.text_field :postal_cd %>
  </div>
  <div class="field">
    <%= f.label "住所１" %><br />
    <%= f.text_field :address1 %>
  </div>
  <div class="field">
    <%= f.label "住所２" %><br />
    <%= f.text_field :address2 %>
  </div>
  <div class="field">
    <%= f.label "電話番号" %><br />
    <%= f.text_field :tel_no %>
  </div>
  <div class="field">
    <%= f.label "FAX番号" %><br />
    <%= f.text_field :fax_no %>
  </div>
  <div class="field">
    <%= f.label "携帯１" %><br />
    <%= f.text_field :mobile_tel_no1 %>
  </div>
  <div class="field">
    <%= f.label "携帯２" %><br />
    <%= f.text_field :mobile_tel_no2 %>
  </div>
  <div class="field">
    <%= f.label "緊急連絡先" %><br />
    <%= f.text_field :emergency_tel_no %>
  </div>
  <div class="field">
    <%= f.label "生年月日" %><br />
    <%= f.date_select :birth_date %>
  </div>
  <div class="field">
    <%= f.label "最寄駅" %><br />
    <%= f.text_field :station %>
  </div>
  <div class="field">
    <%= f.label "出身地" %><br />
    <%= f.text_field :birth_place %>
  </div>
  <div class="field">
    <%= f.label "最終学歴" %><br />
    <%= f.text_field :education_level %>
  </div>
  <div class="field">
    <%= f.label "備考" %><br />
    <%= f.text_area :other %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/employee_masters/edit.html.erb
<%= render '/layouts/header' %>
<h2>従業員マスタ　更新</h2>

<%= render 'form', { employee_master: @employee_master, position_masters: @position_masters,
                     unit_masters: @unit_masters } %>

<%= link_to '照会', @employee_master %> |
<%= link_to '戻る', employee_masters_path %>

app/views/employee_masters/index.html.erb
<%= render '/layouts/header' %>
<h2>従業員マスタ　一覧</h2>

<%= link_to '新規登録', new_employee_master_path %>
<br ><table id="default">
  <thead>
    <tr>
      <th>社員番号</th>
      <th>氏名（漢字）</th>
      <th>氏名（かな）</th>
      <th>職制</th>
      <th>部署名</th>
      <th>eメールアドレス1</th>
      <th>備考</th>
      <th colspan=3></th>
    </tr>
  </thead>

  <tbody>
    <% @employee_masters.each do |employee_master| %>
    <tr>
      <td><%= employee_master.employee_cd %></td>
      <td><%= employee_master.employee_name %></td>
      <td><%= employee_master.employee_name_kana %></td>
      <td><%= employee_master.position_master.position_name %></td>
      <td><%= employee_master.unit_master.unit_name %></td>
      <td><%= employee_master.email_address1 %></td>
      <td><%= employee_master.other %></td>
      <td><%= link_to '照会', employee_master %></td>
      <td><%= link_to '更新', edit_employee_master_path(employee_master) %></td>
      <td><%= link_to '削除', employee_master, method: :delete, data: { confirm: '削除してよろしいですか？' } %></td>
    </tr>
    <% end %>
  </tbody>
</table>
<br />

app/views/employee_masters/new.html.erb
<%= render '/layouts/header' %>
<h2>従業員マスタ　新規登録</h2>

<%= render 'form', { employee_master: @employee_master, position_masters: @position_masters,
                     unit_masters: @unit_masters } %>

<%= link_to '戻る', employee_masters_path %>

app/views/employee_masters/show.html.erb
<%= render '/layouts/header' %>
<h2>従業員マスタ　照会</h2>
<p>
  <strong>社員番号:</strong>
  <%= @employee_master.employee_cd %>
</p>

<p>
  <strong>氏名（漢字）:</strong>
  <%= @employee_master.employee_name %>
</p>

<p>
  <strong>氏名（かな）:</strong>
  <%= @employee_master.employee_name_kana %>
</p>

<p>
  <strong>職制:</strong>
  <%= @employee_master.position_id %>
</p>

<p>
  <strong>部署名:</strong>
  <%= @employee_master.unit_id %>
</p>

<p>
  <strong>eメールアドレス1:</strong>
  <%= @employee_master.email_address1 %>
</p>

<p>
  <strong>eメールアドレス2:</strong>
  <%= @employee_master.emai_address2 %>
</p>

<p>
  <strong>郵便番号:</strong>
  <%= @employee_master.postal_cd %>
</p>

<p>
  <strong>住所1:</strong>
  <%= @employee_master.address1 %>
</p>

<p>
  <strong>住所2:</strong>
  <%= @employee_master.address2 %>
</p>

<p>
  <strong>電話番号:</strong>
  <%= @employee_master.tel_no %>
</p>

<p>
  <strong>FAX番号:</strong>
  <%= @employee_master.fax_no %>
</p>

<p>
  <strong>携帯1:</strong>
  <%= @employee_master.mobile_tel_no1 %>
</p>

<p>
  <strong>携帯2:</strong>
  <%= @employee_master.mobile_tel_no2 %>
</p>

<p>
  <strong>緊急連絡先:</strong>
  <%= @employee_master.emergency_tel_no %>
</p>

<p>
  <strong>生年月日:</strong>
  <%= @employee_master.birth_date %>
</p>

<p>
  <strong>最寄駅:</strong>
  <%= @employee_master.station %>
</p>

<p>
  <strong>出生地:</strong>
  <%= @employee_master.birth_place %>
</p>

<p>
  <strong>最終学歴:</strong>
  <%= @employee_master.education_level %>
</p>

<p>
  <strong>備考:</strong>
  <%= @employee_master.other %>
</p>


<%= link_to '更新', edit_employee_master_path(@employee_master) %> |
<%= link_to '戻る', employee_masters_path %>