config/routes.rb
Ordersheet::Application.routes.draw do
  get "top/index"
  resources :order_dates

  resources :unit_masters

  resources :position_masters

  resources :payment_site_masters

  resources :order_arrival_dates

  resources :order_break_times

  resources :order_charge_people

  resources :order_infos

  resources :business_masters

  resources :project_masters

  resources :company_masters

  resources :employee_masters

  root to: 'top#index'

end

app/models/order_date.rb
class OrderDate < ActiveRecord::Base
  belongs_to :order_info
end

app/controllers/order_dates_controller.rb
class OrderDatesController < ApplicationController
  before_action :set_order_date, only: [:show, :edit, :update, :destroy]

  # GET /order_dates
  # GET /order_dates.json
  def index
    @order_dates = OrderDate.all
  end

  # GET /order_dates/1
  # GET /order_dates/1.json
  def show
  end

  # GET /order_dates/new
  def new
    @order_date = OrderDate.new
  end

  # GET /order_dates/1/edit
  def edit
  end

  # POST /order_dates
  # POST /order_dates.json
  def create
    @order_date = OrderDate.new(order_date_params)

    respond_to do |format|
      if @order_date.save
        format.html { redirect_to @order_date, notice: 'Order date was successfully created.' }
        format.json { render 'show', status: :created, location: @order_date }
      else
        format.html { render 'new' }
        format.json { render json: @order_date.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /order_dates/1
  # PATCH/PUT /order_dates/1.json
  def update
    respond_to do |format|
      if @order_date.update(order_date_params)
        format.html { redirect_to @order_date, notice: 'Order date was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render 'edit' }
        format.json { render json: @order_date.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /order_dates/1
  # DELETE /order_dates/1.json
  def destroy
    @order_date.destroy
    respond_to do |format|
      format.html { redirect_to order_dates_url }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_order_date
      @order_date = OrderDate.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def order_date_params
      params.require(:order_date).permit(:order_id, :order_date)
    end
end

app/views/order_dates/_form.html.erb
<%= form_for(order_date) do |f| %>
  <% if order_date.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(order_date.errors.count, "error") %> prohibited this order_date from being saved:</h2>

      <ul>
      <% order_date.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :order_id %><br />
    <%= f.number_field :order_id %>
  </div>
  <div class="field">
    <%= f.label :order_date %><br />
    <%= f.date_select :order_date %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/order_dates/edit.html.erb
<h1>Editing order_date</h1>

<%= render 'form', order_date: @order_date %>

<%= link_to 'Show', @order_date %> |
<%= link_to 'Back', order_dates_path %>

app/views/order_dates/index.html.erb
<h1>Listing order_dates</h1>

<table>
  <thead>
    <tr>
      <th>Order</th>
      <th>Order date</th>
      <th></th>
      <th></th>
      <th></th>
    </tr>
  </thead>

  <tbody>
    <% @order_dates.each do |order_date| %>
    <tr>
      <td><%= order_date.order_id %></td>
      <td><%= order_date.order_date %></td>
      <td><%= link_to 'Show', order_date %></td>
      <td><%= link_to 'Edit', edit_order_date_path(order_date) %></td>
      <td><%= link_to 'Destroy', order_date, method: :delete, data: { confirm: 'Are you sure?' } %></td>
    </tr>
    <% end %>
  </tbody>
</table>

<br />

<%= link_to 'New Order date', new_order_date_path %>

app/views/order_dates/new.html.erb
<h1>New order_date</h1>

<%= render 'form', order_date: @order_date %>

<%= link_to 'Back', order_dates_path %>

app/views/order_dates/show.html.erb
<p>
  <strong>Order:</strong>
  <%= @order_date.order_id %>
</p>

<p>
  <strong>Order date:</strong>
  <%= @order_date.order_date %>
</p>


<%= link_to 'Edit', edit_order_date_path(@order_date) %> |
<%= link_to 'Back', order_dates_path %>